### ISSUE TITLE
arama-indirme hatası

### ISSUE THREAD

**Issue by celikhasan** [korayal/service.subtitles.divxplanet#3]
Raspberry pi (b+ model) üzerine openelec 5.0.8 kullanıyorum. Sizin 0.0.11 versiyonu ekli. 
Sorunumun birkaç ayağı var. Birincisi, divxplanetten özellikle dizi ararken baya uzun süre bekliyor.(pc'den açarken sayfa normal yükleniyor, open subtitles eklentisinde de çok çok fazla altyazı bulmadıysa normal sürede arama sonuçları ekrana geliyor) 
İkincisi, indirme sorunu yaşadım. Logları karıştırırken divxplanet'in eski adresinden indirmeye çalıştığını farkettim, bu adresi de xml dosyasından aldığını gördüm. Onu değiştirince indirdi fakat bu sefer de ilkinde dosyayı dizinin olduğu yere kopyalamadı, diğer denemelerde de rar dosyasını açarken sorun yaşadı. 
Logları aşağıya kopyalıyorum: 

-------------------------------------------------------------------
İlk durumla ilgili loglar (8 dakikada bulmuş)
22:27:17 T:1185760320  NOTICE: Divxplanet: searching subtitles for The Big Bang Theory  9 8
22:27:17 T:1185760320  NOTICE: Divxplanet: Finding dizi: The Big Bang Theory ()
22:27:58 T:1185760320  NOTICE: Divxplanet: got media url http://altyazi.org/sub/m/13274/The-Big-Bang-Theory.html
22:35:52 T:1185760320  NOTICE: Divxplanet: found 3 subtitles

------------------------------------------------------------------------------------
ikinci durum için loglar:
21:31:32 T:1287648320  NOTICE: Divxplanet: searching subtitles for The Big Bang Theory  9 8
21:31:32 T:1287648320  NOTICE: Divxplanet: Finding dizi: The Big Bang Theory ()
21:32:00 T:1287648320  NOTICE: Divxplanet: got media url http://altyazi.org/sub/m/13274/The-Big-Bang-Theory.html
21:36:48 T:1287648320  NOTICE: Divxplanet: found 3 subtitles
21:36:57 T:1287648320  NOTICE: Thread LanguageInvoker start, auto delete: false
21:36:59 T:1287648320  NOTICE: -->Python Interpreter Initialized<--
21:37:08 T:1152205888   ERROR: GetDirectory - Error getting plugin://service.subtitles.divxplanet/?action=download&link=/sub/s/377355/The-Big-Bang-Theory.html&lang=tr&description=The Big Bang Theory S09E08 The Mystery Date Observation.tr
21:37:11 T:1287648320  NOTICE: Thread LanguageInvoker start, auto delete: false

--------------------------------------------------------------------------------------------------------
addon.xml dosyasında <addon id="service.subtitles.altyazi.org" değişikliği yaptıktan sonra bir film denemesi yaptım, başarılı bir şekilde indirdi. ilgili loglar:
22:24:15 T:1177371712  NOTICE: Divxplanet: searching subtitles for Masaan 2015
22:24:15 T:1177371712  NOTICE: Divxplanet: Finding film: Masaan (2015)
22:24:56 T:1177371712  NOTICE: Divxplanet: got media url http://altyazi.org/sub/m/52229/Masaan.html
22:25:46 T:1177371712  NOTICE: Divxplanet: found a subtitle with description: Masaan.2015.2CD.DvDRip.x264.AC3.5.1.ESub[DDR]
22:25:47 T:1177371712  NOTICE: Divxplanet: found a subtitle with description: Masaan (2015) 1080p BDRip - x264 DTS HDMA - DUS
22:25:47 T:1177371712  NOTICE: Divxplanet: found 2 subtitles
22:26:00 T:1345143872  NOTICE: Thread LanguageInvoker start, auto delete: false
22:26:03 T:1345143872  NOTICE: -->Python Interpreter Initialized<--
22:26:16 T:1345143872  NOTICE: Divxplanet: o yoldayiz /sub/s/375521/Masaan.html
22:26:27 T:1345143872  NOTICE: Divxplanet: Fetching subtitles using url http://altyazi.org//sub/s/375521/Masaan.html
22:26:27 T:1345143872  NOTICE: Divxplanet: Saving subtitles to '/storage/.kodi/userdata/addon_data/service.subtitles.divxplanet/temp/(375521)Masaan_23.976fps_1CD_English_SubRip_DiVXPlanet.zip'
22:26:31 T:1345143872  NOTICE: Divxplanet: Unpacked files in '/storage/.kodi/userdata/addon_data/service.subtitles.divxplanet/temp'
22:26:31 T:1345143872  NOTICE: Divxplanet: Unpacked subtitles file 'Masaan.2015.2CD.DvDRip.x264.AC3.5.1.ESub[DDR].srt'
22:26:31 T:1345143872  NOTICE: Divxplanet: Subtitles saved to '/storage/.kodi/userdata/addon_data/service.subtitles.divxplanet/temp/(375521)Masaan_23.976fps_1CD_English_SubRip_DiVXPlanet.zip'
22:26:31 T:1120924736 WARNING: SMBFile::OpenForWrite() called with overwriting enabled! - smb://pi:xxxxxxx@xxxxxx/Paylasim/torrent/Masaan%20(2015)%20Hindi%20720p%20DVDRip%20x264%20AAC%20E-Sub%20-%3dBy%20%40%20Kamalesh%3d-/Masaan%20(2015)%20Hindi%20720p%20DVDRip%20x264%20AAC%20E-Sub%20-%3dBy%20%40%20Kamalesh%3d-.en.srt

------------------------------------------------------------------------------------------
Aynı denemeyi big bang theory için yapınca ilk seferinde altyazıyı indirmiş fakat video dosyasının olduğu yere yazmamış görünüyor. Diğerlerinde de rar dosyasını açamadığı görülüyor. Tempteki srt dosyasını silip denesem olurmuş. 

22:27:17 T:1185760320  NOTICE: Divxplanet: searching subtitles for The Big Bang Theory  9 8
22:27:17 T:1185760320  NOTICE: Divxplanet: Finding dizi: The Big Bang Theory ()
22:27:58 T:1185760320  NOTICE: Divxplanet: got media url http://altyazi.org/sub/m/13274/The-Big-Bang-Theory.html
22:35:52 T:1185760320  NOTICE: Divxplanet: found 3 subtitles
22:40:42 T:1101874240  NOTICE: Thread JobWorker start, auto delete: true
22:40:42 T:1120924736  NOTICE: Thread LanguageInvoker start, auto delete: false
22:40:43 T:1120924736  NOTICE: -->Python Interpreter Initialized<--
22:40:52 T:1120924736  NOTICE: Divxplanet: o yoldayiz /sub/s/377355/The-Big-Bang-Theory.html
22:41:33 T:1120924736  NOTICE: Divxplanet: Fetching subtitles using url http://altyazi.org//sub/s/377355/The-Big-Bang-Theory.html
22:41:33 T:1120924736  NOTICE: Divxplanet: Saving subtitles to '/storage/.kodi/userdata/addon_data/service.subtitles.divxplanet/temp/(377355)The_Big_Bang_Theory_23.976fps_1CD_Turkce_SubRip_DiVXPlanet.rar'
22:41:36 T:1120924736  NOTICE: Divxplanet: Unpacked files in '/storage/.kodi/userdata/addon_data/service.subtitles.divxplanet/temp'
22:41:36 T:1120924736  NOTICE: Divxplanet: Subtitles saved to '/storage/.kodi/userdata/addon_data/service.subtitles.divxplanet/temp/(377355)The_Big_Bang_Theory_23.976fps_1CD_Turkce_SubRip_DiVXPlanet.rar'
22:41:46 T:1223685184  NOTICE: Thread LanguageInvoker start, auto delete: false
22:41:48 T:1223685184  NOTICE: -->Python Interpreter Initialized<--
22:41:57 T:1223685184  NOTICE: Divxplanet: o yoldayiz /sub/s/377355/The-Big-Bang-Theory.html
22:42:38 T:1223685184  NOTICE: Divxplanet: Fetching subtitles using url http://altyazi.org//sub/s/377355/The-Big-Bang-Theory.html
22:42:38 T:1223685184  NOTICE: Divxplanet: Saving subtitles to '/storage/.kodi/userdata/addon_data/service.subtitles.divxplanet/temp/(377355)The_Big_Bang_Theory_23.976fps_1CD_Turkce_SubRip_DiVXPlanet.rar'
22:43:00 T:1223685184  NOTICE: Divxplanet: Failed to unpack subtitles in '/storage/.kodi/userdata/addon_data/service.subtitles.divxplanet/temp'
22:43:00 T:1223685184  NOTICE: Divxplanet: Subtitles saved to '/storage/.kodi/userdata/addon_data/service.subtitles.divxplanet/temp/(377355)The_Big_Bang_Theory_23.976fps_1CD_Turkce_SubRip_DiVXPlanet.rar'

**Comment by korayal** [comment]
Son guncel service.py dosyasini degistirip tekrar deneyebilir misiniz? yahut bir sonraki guncellemeyi de bekleyebilirsiniz.

Sure konusunda tam olarak neler degisir bilemiyorum. Raspberry PI zaten hali hazirda kodi calistirirken oldukca cok kaynak tuketiyordur. Bu yuzden site gezme indirme vb. islemler vakit aliyor olabilir.
