### ISSUE TITLE
EXCEPTION Thrown (PythonToCppException)

### ISSUE THREAD

**Issue by juk47ht** [korayal/service.subtitles.divxplanet#5]
Uzun bir suredir maalesef bu add-on bende calismiyor. Asagidakine benzer bir hata aliyorum. 

> 17:48:49 T:1824  NOTICE: [SEARCH !TVSHOW] Divxplanet: searching subtitles for Trolls 2016
> 17:48:49 T:1824  NOTICE: getting media url
> 17:48:51 T:1824  NOTICE: Getting uri: http://www.altyazi.org/index.php?page=arama&arama=Trolls+(2016)
> 17:49:21 T:1824  NOTICE: Got uri [522]: http://www.altyazi.org/index.php?page=arama&arama=Trolls+(2016)
> 17:49:21 T:1824   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.ValueError'>
>                                             Error Contents: No valid results
>                                             Traceback (most recent call last):
>                                               File "C:\Users\ck\AppData\Roaming\Kodi\addons\service.subtitles.divxplanet\service.py", line 337, in <module>
>                                                 search(item)
>                                               File "C:\Users\ck\AppData\Roaming\Kodi\addons\service.subtitles.divxplanet\service.py", line 174, in search
>                                                 tvurl = get_media_url(["film", title, year])
>                                               File "C:\Users\ck\AppData\Roaming\Kodi\addons\service.subtitles.divxplanet\service.py", line 95, in get_media_url
>                                                 raise ValueError('No valid results')
>                                             ValueError: No valid results
>                                             -->End of Python script error report<--
> 17:49:21 T:5892   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://service.subtitles.divxplanet/?action=search&languages=English&preferredlanguage=English

**Comment by korayal** [comment]
An itibariyle altyazi.org sitesi acilmiyor. Bu sebeple konuyu henuz inceleyemiyorum. altyazi.org adresine girebildikten sonra tekrar deneyip olusacak loglari gonderebilirseniz bakabilirim.

**Comment by juk47ht** [comment]
Anlasilan site kapanmis: https://twitter.com/altyazi_org/status/828630794134491136

**Comment by korayal** [comment]
Evet duyurudan haberim var. Eklenti icin henuz bir karar vermedim. Diger siteyi de henuz incelemedim. Artik yogunluk durumuma gore bir bakacagim.
