### ISSUE TITLE
Error Type: <class 'bs4.FeatureNotFound'>

### ISSUE THREAD

**Issue by caglarkoksal** [korayal/service.subtitles.divxplanet#6]

**Comment by korayal** [comment]
Selamlar,

Bu konuda baska bir arkadas benden once bir eklenti cikarmisti. O sebeple kodi'nin eklenti veritabanina yuklemedim.

Bahsettiginiz sorunun cozumunu develop branchinde halletmistim, ama henuz release etmemistim. Su adrestekini kullanabilirsiniz:

https://github.com/korayal/service.subtitles.planetdp/archive/develop.zip
