### ISSUE TITLE
Kodi veritabanindaki surum guncel degil

### ISSUE THREAD

**Issue by juk47ht** [korayal/service.subtitles.divxplanet#7]
Oncelikle bu eklentiyi yeniden guncelledigin icin cok tesekkurler. 

Kodi'nin resmi add-on veritabanindaki surum 0.1.1, en son 2014'te guncellenmis: https://kodi.tv/addon/subtitles/divxplanet

Kodi'nin veritabaninda 'planetdp' ile ilgili bir baska eklenti yok. Acaba bu eklentinin en son surumunu yeniden yukleyebilir misin? Eklentinin sahibi olarak hala sen gorundugun icin sanirim buyuk bir problemle karsilasmazsin yukleme yaparken.

Tesekkurler.

**Comment by korayal** [comment]
[Surada](https://github.com/korayal/service.subtitles.planetdp/issues/6#issuecomment-302413950) da bahsettigim uzere PlanetDP ile ilgili bir eklenti uzerine calisan baska bir arkadas var. Bu sebeple Kodi veritabanina yukleme yapmadim. Arzu ederseniz burada bulunan surumu manuel olarak ayni linkte bahsi gecen adresten yukleyerek kullanabilirsiniz. (tam randimanli calisacagi konusunda soz veremiyorum)
